"use client";

import { useEffect, useMemo, useState } from "react";

type View = "Dashboard" | "My Groups" | "Leaderboard" | "Activity" | "Profile" | "Settings";
type Modal = "submit" | "waiver" | "join" | "create" | null;

const members = [
  { name: "Sarah", initials: "SK", streak: 18, solved: 86, rate: 97, longest: 23, failed: 1, color: "mint" },
  { name: "Mike", initials: "MC", streak: 15, solved: 74, rate: 94, longest: 15, failed: 2, color: "blue" },
  { name: "James", initials: "JL", streak: 13, solved: 69, rate: 92, longest: 19, failed: 2, color: "violet" },
  { name: "Daniel", initials: "DP", streak: 8, solved: 61, rate: 88, longest: 12, failed: 4, color: "orange" },
];

const initialActivity = [
  { icon: "✓", tone: "green", text: <><strong>Sarah</strong> completed today’s challenge.</>, time: "18 min ago" },
  { icon: "↗", tone: "blue", text: <><strong>James</strong> submitted <em>Two Sum</em>.</>, time: "42 min ago" },
  { icon: "½", tone: "violet", text: <><strong>Daniel</strong> is 1/2 completed.</>, time: "1 hr ago" },
  { icon: "🔥", tone: "orange", text: <><strong>Sarah</strong> reached an 18-day streak.</>, time: "Yesterday" },
  { icon: "×", tone: "red", text: <><strong>Alex</strong> missed yesterday’s commitment.</>, time: "Yesterday" },
];

export function AccountabilityApp({ viewerName, signedIn }: { viewerName: string; signedIn: boolean }) {
  const [view, setView] = useState<View>("Dashboard");
  const [modal, setModal] = useState<Modal>(null);
  const [submitted, setSubmitted] = useState(false);
  const [toast, setToast] = useState("");
  const [seconds, setSeconds] = useState(2 * 3600 + 34 * 60 + 18);

  useEffect(() => {
    const timer = window.setInterval(() => setSeconds((s) => Math.max(0, s - 1)), 1000);
    return () => window.clearInterval(timer);
  }, []);
  useEffect(() => {
    if (!toast) return;
    const timer = window.setTimeout(() => setToast(""), 3200);
    return () => window.clearTimeout(timer);
  }, [toast]);

  const time = useMemo(() => `${Math.floor(seconds / 3600)}h ${String(Math.floor((seconds % 3600) / 60)).padStart(2, "0")}m ${String(seconds % 60).padStart(2, "0")}s`, [seconds]);
  const completeSubmission = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setSubmitted(true); setModal(null); setToast("Problem submitted — today’s challenge is complete! 🔥");
  };

  return <div className="app-shell">
    <aside className="sidebar">
      <button className="brand" onClick={() => setView("Dashboard")} aria-label="Commit dashboard"><span className="brand-mark">C</span><span>commit<span className="brand-dot">.</span></span></button>
      <nav aria-label="Primary navigation">{(["Dashboard", "My Groups", "Leaderboard", "Activity"] as View[]).map((item) => <button key={item} className={view === item ? "nav-item active" : "nav-item"} onClick={() => setView(item)}><span className="nav-icon">{item === "Dashboard" ? "⌂" : item === "My Groups" ? "♧" : item === "Leaderboard" ? "♛" : "◉"}</span>{item}</button>)}</nav>
      <div className="side-bottom"><button className={view === "Settings" ? "nav-item active" : "nav-item"} onClick={() => setView("Settings")}><span className="nav-icon">⚙</span>Settings</button><button className={view === "Profile" ? "profile-tile selected" : "profile-tile"} onClick={() => setView("Profile")}><span className="avatar blue">MC</span><span><b>{viewerName} Chen</b><small>@mikecodes</small></span><span className="dots">•••</span></button></div>
    </aside>
    <main>
      <header className="mobile-header"><button className="brand" onClick={() => setView("Dashboard")}><span className="brand-mark">C</span>commit<span className="brand-dot">.</span></button><button className="icon-button" onClick={() => setView("Profile")}>MC</button></header>
      {view === "Dashboard" && <Dashboard name={viewerName} time={time} submitted={submitted} onSubmit={() => setModal("submit")} onWaiver={() => setModal("waiver")} onViewLeaderboard={() => setView("Leaderboard")} onViewActivity={() => setView("Activity")} />}
      {view === "My Groups" && <Groups onJoin={() => setModal("join")} onCreate={() => setModal("create")} />}
      {view === "Leaderboard" && <Leaderboard full />}{view === "Activity" && <Activity full />}
      {view === "Profile" && <Profile name={viewerName} signedIn={signedIn} />}{view === "Settings" && <Settings />}
    </main>
    <nav className="mobile-nav" aria-label="Mobile navigation">{(["Dashboard", "My Groups", "Leaderboard", "Activity"] as View[]).map((item) => <button key={item} className={view === item ? "active" : ""} onClick={() => setView(item)}><span>{item === "Dashboard" ? "⌂" : item === "My Groups" ? "♧" : item === "Leaderboard" ? "♛" : "◉"}</span><small>{item === "My Groups" ? "Groups" : item}</small></button>)}</nav>
    {modal && <ModalDialog type={modal} onClose={() => setModal(null)} onSubmit={completeSubmission} onDone={(message) => { setModal(null); setToast(message); }} />}{toast && <div className="toast" role="status"><span>✓</span>{toast}</div>}
  </div>;
}

function Dashboard({ name, time, submitted, onSubmit, onWaiver, onViewLeaderboard, onViewActivity }: { name: string; time: string; submitted: boolean; onSubmit: () => void; onWaiver: () => void; onViewLeaderboard: () => void; onViewActivity: () => void }) {
  const count = submitted ? 2 : 1;
  return <div className="page dashboard-page">
    <section className="welcome"><div><p className="eyebrow">SATURDAY, AUGUST 15</p><h1>Good evening, {name} <span>👋</span></h1><p>You’re one problem away. Finish strong.</p></div><div className="header-actions"><button className="icon-button" aria-label="Notifications">♢<span className="notification-dot" /></button><button className="primary small" onClick={onSubmit}>＋ Submit problem</button></div></section>
    <section className="today-card"><div className="today-head"><div className="group-title"><span className="code-badge">&lt;/&gt;</span><div><p>TODAY · LEETCODE GRIND</p><h2>{submitted ? "Challenge complete" : "One more. You’ve got this."}</h2></div></div><span className={submitted ? "status completed" : "status pending"}>{submitted ? "COMPLETED" : "IN PROGRESS"}</span></div><div className="today-grid">
      <div className="progress-side"><div className="progress-copy"><span><b>{count}</b> / 2 problems</span><small>{count * 50}% complete</small></div><div className="progress-track"><span style={{ width: `${count * 50}%` }} /></div><div className="problem-list"><div className="problem done"><span className="check">✓</span><div><b>Valid Palindrome</b><small>Submitted at 6:42 PM</small></div><span className="difficulty">EASY</span><button aria-label="Open submission">↗</button></div><div className={submitted ? "problem done" : "problem open"}><span className={submitted ? "check" : "problem-number"}>{submitted ? "✓" : "2"}</span><div><b>{submitted ? "Two Sum" : "Problem 2"}</b><small>{submitted ? "Submitted just now" : "Not submitted yet"}</small></div>{submitted ? <span className="difficulty">EASY</span> : <button className="outline compact" onClick={onSubmit}>Submit problem&nbsp; →</button>}</div></div></div>
      <div className="deadline-side"><p className="eyebrow">TIME REMAINING</p><div className="timer">{submitted ? "Done!" : time}</div><p className="deadline">Deadline · 11:59 PM ET</p><div className="risk-box"><span>$</span><p><b>$30 at risk</b><small>$10 to each of 3 other members</small></p></div><button className="text-button" onClick={onWaiver} disabled={submitted}>{submitted ? "Waiver not needed" : "Request a waiver"} <span>→</span></button><small className="cutoff">Waiver cutoff · 9:59 PM</small></div>
    </div></section>
    <section className="stat-row"><article className="stat-card"><span className="stat-icon orange">🔥</span><div><p>CURRENT STREAK</p><strong>15 <small>days</small></strong><span className="positive">↑ Personal best</span></div></article><article className="stat-card"><span className="stat-icon blue">✓</span><div><p>SUCCESSFUL DAYS</p><strong>47</strong><span>94% completion rate</span></div></article><article className="stat-card"><span className="stat-icon violet">⌘</span><div><p>PROBLEMS SOLVED</p><strong>{submitted ? 75 : 74}</strong><span>+12 this week</span></div></article><article className="stat-card"><span className="stat-icon red">↘</span><div><p>MISSED DAYS</p><strong>2</strong><span>$60 paid total</span></div></article></section>
    <div className="dashboard-bottom"><Leaderboard onView={onViewLeaderboard} /><Activity onView={onViewActivity} /></div>
  </div>;
}

function Leaderboard({ full = false, onView }: { full?: boolean; onView?: () => void }) { return <div className={full ? "page inner-page" : "panel leaderboard-panel"}>{full && <PageTitle eyebrow="LEETCODE GRIND" title="Leaderboard" subtitle="Consistency wins. Rankings update after each completed day." />}<div className="panel-head"><div><h3>{full ? "Group standings" : "Leaderboard"}</h3>{!full && <p>LeetCode Grind · This month</p>}</div>{!full && <button className="text-link" onClick={onView}>View full board →</button>}</div><div className="leader-table"><div className="leader-header"><span>RANK</span><span>MEMBER</span><span>STREAK</span>{full && <><span>COMPLETION</span><span>LONGEST</span><span>MISSED</span></>}</div>{members.map((member, i) => <div className={member.name === "Mike" ? "leader-row current" : "leader-row"} key={member.name}><span className={`rank rank-${i + 1}`}>{i + 1}</span><span className="member"><span className={`avatar ${member.color}`}>{member.initials}</span><span><b>{member.name}{member.name === "Mike" && <em>YOU</em>}</b><small>{member.solved} problems</small></span></span><span className="streak">🔥 <b>{member.streak}</b> days</span>{full && <><span><b>{member.rate}%</b><small>successful</small></span><span><b>{member.longest}</b><small>days</small></span><span><b>{member.failed}</b><small>days</small></span></>}</div>)}</div></div>; }
function Activity({ full = false, onView }: { full?: boolean; onView?: () => void }) { return <div className={full ? "page inner-page" : "panel activity-panel"}>{full && <PageTitle eyebrow="THE FEED" title="Group activity" subtitle="What your crew has been up to." />}<div className="panel-head"><div><h3>{full ? "Today" : "Recent activity"}</h3>{!full && <p>Your group is on a roll.</p>}</div>{!full && <button className="text-link" onClick={onView}>See all →</button>}</div><div className="activity-list">{[...initialActivity, ...(full ? initialActivity.slice(0, 3) : [])].map((item, i) => <div className="activity-item" key={i}><span className={`activity-icon ${item.tone}`}>{item.icon}</span><div><p>{item.text}</p><small>{i > 4 ? "2 days ago" : item.time}</small></div></div>)}</div></div>; }

function Groups({ onJoin, onCreate }: { onJoin: () => void; onCreate: () => void }) { return <div className="page inner-page"><PageTitle eyebrow="YOUR CREW" title="My groups" subtitle="Build momentum with people who keep you honest." actions={<><button className="outline" onClick={onJoin}>Join with code</button><button className="primary" onClick={onCreate}>＋ Create group</button></>} /><div className="group-grid"><article className="group-card featured"><div className="group-card-top"><span className="code-badge">&lt;/&gt;</span><span className="status active">ACTIVE</span></div><h2>LeetCode Grind</h2><p>Daily problem-solving for interview season. No excuses, just reps.</p><div className="member-stack">{members.map(m => <span className={`avatar ${m.color}`} key={m.name}>{m.initials}</span>)}<small>4 members</small></div><div className="rules"><span><small>DAILY GOAL</small><b>2 problems</b></span><span><small>DEADLINE</small><b>11:59 PM ET</b></span><span><small>PENALTY</small><b>$10 × 3</b></span></div><button className="primary wide">Open group →</button></article><button className="empty-group" onClick={onCreate}><span>＋</span><b>Start another challenge</b><small>Create a group and invite your friends.</small></button></div></div>; }
function Profile({ name, signedIn }: { name: string; signedIn: boolean }) { return <div className="page inner-page"><PageTitle eyebrow="PLAYER PROFILE" title={`${name} Chen`} subtitle="@mikecodes · America/New_York" /><div className="profile-grid"><article className="profile-card"><span className="avatar huge blue">MC</span><h2>{name} Chen</h2><p>Building things and grinding algorithms.</p><div className="profile-stats"><span><b>15</b><small>streak</small></span><span><b>74</b><small>solved</small></span><span><b>94%</b><small>completion</small></span></div>{signedIn ? <a className="outline wide link-button" href="/signout-with-chatgpt?return_to=/">Log out</a> : <a className="primary wide link-button" href="/signin-with-chatgpt?return_to=/">Sign in with ChatGPT</a>}</article><article className="panel"><div className="panel-head"><h3>Recent achievements</h3></div>{[["🔥","Two week heater","Maintained a 14-day streak"],["⚡","Early bird","Completed before noon 10 times"],["◈","Fifty club","Solved 50 total problems"]].map(x => <div className="achievement" key={x[1]}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div></div>)}</article></div></div>; }
function Settings() { return <div className="page inner-page"><PageTitle eyebrow="PREFERENCES" title="Settings" subtitle="Keep your account and challenge notifications dialed in." /><div className="settings-card"><Setting title="Daily reminders" copy="Get a nudge when your deadline is getting close." /><Setting title="Group activity" copy="Receive updates when teammates complete or request waivers." /><Setting title="Streak milestones" copy="Celebrate when you or your teammates hit a new streak." /><div className="timezone-row"><div><b>Timezone</b><p>Used for personal display. Group deadlines follow the group timezone.</p></div><select aria-label="Timezone"><option>America/New_York (ET)</option><option>America/Los_Angeles (PT)</option><option>Europe/London (GMT)</option></select></div></div></div>; }
function Setting({ title, copy }: { title: string; copy: string }) { const [on, setOn] = useState(true); return <div className="setting"><div><b>{title}</b><p>{copy}</p></div><button className={on ? "toggle on" : "toggle"} aria-pressed={on} onClick={() => setOn(!on)}><span /></button></div>; }
function PageTitle({ eyebrow, title, subtitle, actions }: { eyebrow: string; title: string; subtitle: string; actions?: React.ReactNode }) { return <section className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></div>{actions && <div className="title-actions">{actions}</div>}</section>; }

function ModalDialog({ type, onClose, onSubmit, onDone }: { type: Exclude<Modal, null>; onClose: () => void; onSubmit: (e: React.FormEvent<HTMLFormElement>) => void; onDone: (message: string) => void }) {
  const isSubmit = type === "submit", isWaiver = type === "waiver", isJoin = type === "join";
  return <div className="modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close" onClick={onClose} aria-label="Close">×</button><p className="eyebrow">{isSubmit ? "PROOF OF WORK" : isWaiver ? "WAIVER REQUEST" : isJoin ? "JOIN A CHALLENGE" : "NEW CHALLENGE"}</p><h2 id="modal-title">{isSubmit ? "Submit a problem" : isWaiver ? "Request today’s waiver" : isJoin ? "Enter your invite code" : "Create a group"}</h2><p className="modal-intro">{isSubmit ? "Add the problem and a screenshot of your accepted solution." : isWaiver ? "Requests must be submitted by 9:59 PM and approved by your group." : isJoin ? "Review the stakes before you commit." : "Set a clear goal and fair consequences for the whole crew."}</p>
    {isSubmit ? <form onSubmit={onSubmit} className="form"><label>Problem title<input required placeholder="e.g. Two Sum" /></label><label>LeetCode URL<input required type="url" placeholder="https://leetcode.com/problems/..." /></label><label>Screenshot proof<span className="upload"><input required type="file" accept="image/*" /><b>↑ Upload accepted solution</b><small>PNG, JPG, or WEBP · max 8 MB</small></span></label><label>Notes <small>OPTIONAL</small><textarea placeholder="What clicked for you?" /></label><button className="primary wide" type="submit">Submit problem →</button></form> : isWaiver ? <form className="form" onSubmit={(e) => { e.preventDefault(); onDone("Waiver requested — your group can now vote."); }}><label>Reason<select required defaultValue=""><option value="" disabled>Choose a category</option><option>Illness</option><option>Emergency</option><option>Travel</option><option>Exam / Academic Conflict</option><option>Personal</option><option>Other</option></select></label><label>What’s going on?<textarea required placeholder="Give your group enough context to vote fairly." /></label><div className="notice">⏱ Submitted 2+ hours before the deadline. Group approval is still required.</div><button className="primary wide" type="submit">Send waiver request</button></form> : isJoin ? <form className="form" onSubmit={(e) => { e.preventDefault(); onDone("Invite accepted — welcome to the challenge!"); }}><label>Invite code<input required placeholder="e.g. GRIND-24" /></label><div className="agreement"><div><span className="code-badge small-code">$</span><div><b>Know what’s at stake</b><p>By joining, you agree that failing a daily commitment may result in a <strong>$10 payment to EACH other member</strong> of the group.</p></div></div><div className="max-penalty"><span>Maximum daily penalty</span><strong>$30</strong></div><label className="checkbox"><input required type="checkbox" /> I understand and explicitly agree to this penalty structure.</label></div><button className="primary wide" type="submit">Agree & join group</button></form> : <form className="form" onSubmit={(e) => { e.preventDefault(); onDone("Group created — your invite code is ready!"); }}><label>Group name<input required placeholder="e.g. LeetCode Grind" /></label><div className="form-row"><label>Problems per day<input required type="number" min="1" defaultValue="2" /></label><label>Penalty per member<input required type="number" min="0" defaultValue="10" /></label></div><label>Daily deadline<input required type="time" defaultValue="23:59" /></label><div className="notice">Payments are simulated in this development version. No real cards are charged.</div><button className="primary wide" type="submit">Create group</button></form>}
  </section></div>;
}
