import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: text("created_at").notNull(), updatedAt: text("updated_at") };
export const users = sqliteTable("users", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), username: text("username").notNull().unique(), profileImage: text("profile_image"), timezone: text("timezone").notNull(), ...timestamps });
export const authAccounts = sqliteTable("auth_accounts", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), passwordHash: text("password_hash").notNull(), passwordSalt: text("password_salt").notNull(), createdAt: text("created_at").notNull() }, t => [uniqueIndex("auth_account_user_unique").on(t.userId)]);
export const authSessions = sqliteTable("auth_sessions", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), tokenHash: text("token_hash").notNull().unique(), expiresAt: text("expires_at").notNull(), createdAt: text("created_at").notNull() }, t => [index("auth_session_token_idx").on(t.tokenHash), index("auth_session_expiry_idx").on(t.expiresAt)]);
export const paymentMethods = sqliteTable("payment_methods", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), provider: text("provider").notNull(), providerCustomerId: text("provider_customer_id").notNull(), providerPaymentMethodId: text("provider_payment_method_id").notNull(), brand: text("brand").notNull(), last4: text("last4").notNull(), expiryMonth: integer("expiry_month").notNull(), expiryYear: integer("expiry_year").notNull(), status: text("status", { enum: ["ACTIVE", "EXPIRED", "REMOVED"] }).notNull().default("ACTIVE"), createdAt: text("created_at").notNull() }, t => [uniqueIndex("payment_method_provider_unique").on(t.provider, t.providerPaymentMethodId), index("payment_method_user_idx").on(t.userId, t.status)]);
export const groups = sqliteTable("groups", { id: text("id").primaryKey(), name: text("name").notNull(), description: text("description").notNull().default(""), ownerId: text("owner_id").notNull().references(() => users.id), inviteCode: text("invite_code").notNull().unique(), dailyRequiredProblems: integer("daily_required_problems").notNull(), penaltyPerParticipant: real("penalty_per_participant").notNull(), deadline: text("deadline").notNull(), timezone: text("timezone").notNull(), challengeStartDate: text("challenge_start_date").notNull(), challengeEndDate: text("challenge_end_date"), status: text("status", { enum: ["DRAFT", "ACTIVE", "ENDED"] }).notNull(), ...timestamps });
export const groupMembers = sqliteTable("group_members", { id: text("id").primaryKey(), groupId: text("group_id").notNull().references(() => groups.id), userId: text("user_id").notNull().references(() => users.id), role: text("role", { enum: ["OWNER", "MEMBER"] }).notNull(), penaltyAgreementAt: text("penalty_agreement_at").notNull(), joinedAt: text("joined_at").notNull(), leftAt: text("left_at") }, t => [uniqueIndex("group_member_unique").on(t.groupId, t.userId)]);
export const dailyCommitments = sqliteTable("daily_commitments", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), groupId: text("group_id").notNull().references(() => groups.id), date: text("date").notNull(), status: text("status", { enum: ["PENDING", "COMPLETED", "WAIVER_PENDING", "WAIVED", "FAILED"] }).notNull().default("PENDING"), completedCount: integer("completed_count").notNull().default(0), requiredCount: integer("required_count").notNull(), completedAt: text("completed_at"), deadline: text("deadline").notNull(), penaltyTriggered: integer("penalty_triggered", { mode: "boolean" }).notNull().default(false), waiverId: text("waiver_id") }, t => [uniqueIndex("commitment_user_group_date_unique").on(t.userId, t.groupId, t.date), index("commitment_deadline_idx").on(t.deadline, t.status)]);
export const problemSubmissions = sqliteTable("problem_submissions", { id: text("id").primaryKey(), commitmentId: text("commitment_id").notNull().references(() => dailyCommitments.id), userId: text("user_id").notNull().references(() => users.id), problemTitle: text("problem_title").notNull(), leetcodeUrl: text("leetcode_url").notNull(), notes: text("notes"), submittedAt: text("submitted_at").notNull() });
export const proofUploads = sqliteTable("proof_uploads", { id: text("id").primaryKey(), submissionId: text("submission_id").notNull().references(() => problemSubmissions.id), objectKey: text("object_key").notNull(), imageUrl: text("image_url").notNull(), uploadedAt: text("uploaded_at").notNull(), verificationStatus: text("verification_status", { enum: ["UNVERIFIED", "ACCEPTED", "REJECTED"] }).notNull().default("UNVERIFIED") });
export const waiverRequests = sqliteTable("waiver_requests", { id: text("id").primaryKey(), requesterId: text("requester_id").notNull().references(() => users.id), groupId: text("group_id").notNull().references(() => groups.id), commitmentId: text("commitment_id").notNull().references(() => dailyCommitments.id), date: text("date").notNull(), reasonCategory: text("reason_category").notNull(), explanation: text("explanation").notNull(), submittedAt: text("submitted_at").notNull(), status: text("status", { enum: ["PENDING", "APPROVED", "REJECTED"] }).notNull().default("PENDING") });
export const waiverVotes = sqliteTable("waiver_votes", { id: text("id").primaryKey(), waiverId: text("waiver_id").notNull().references(() => waiverRequests.id), voterId: text("voter_id").notNull().references(() => users.id), vote: text("vote", { enum: ["APPROVE", "REJECT"] }).notNull(), createdAt: text("created_at").notNull() }, t => [uniqueIndex("waiver_voter_unique").on(t.waiverId, t.voterId)]);
export const streaks = sqliteTable("streaks", { id: text("id").primaryKey(), groupId: text("group_id").notNull().references(() => groups.id), userId: text("user_id").notNull().references(() => users.id), currentStreak: integer("current_streak").notNull().default(0), longestStreak: integer("longest_streak").notNull().default(0), totalSuccessfulDays: integer("total_successful_days").notNull().default(0), totalFailedDays: integer("total_failed_days").notNull().default(0), totalProblemsCompleted: integer("total_problems_completed").notNull().default(0), updatedAt: text("updated_at").notNull() }, t => [uniqueIndex("streak_user_group_unique").on(t.groupId, t.userId)]);
export const penaltyTransactions = sqliteTable("penalty_transactions", { id: text("id").primaryKey(), groupId: text("group_id").notNull().references(() => groups.id), failedUserId: text("failed_user_id").notNull().references(() => users.id), recipientUserId: text("recipient_user_id").notNull().references(() => users.id), dailyCommitmentId: text("daily_commitment_id").notNull().references(() => dailyCommitments.id), amount: real("amount").notNull(), status: text("status", { enum: ["PENDING", "PROCESSING", "COMPLETED", "FAILED"] }).notNull().default("PENDING"), createdAt: text("created_at").notNull(), processedAt: text("processed_at"), paymentProviderTransactionId: text("payment_provider_transaction_id") }, t => [uniqueIndex("penalty_commitment_recipient_unique").on(t.dailyCommitmentId, t.recipientUserId)]);
export const activityEvents = sqliteTable("activity_events", { id: text("id").primaryKey(), groupId: text("group_id").notNull().references(() => groups.id), actorUserId: text("actor_user_id").references(() => users.id), type: text("type").notNull(), message: text("message").notNull(), createdAt: text("created_at").notNull() }, t => [index("activity_group_created_idx").on(t.groupId, t.createdAt)]);
